### ISSUE TITLE
Should we still support Python 2?

### ISSUE THREAD

**Issue by madebr** [subdownloader/subdownloader#20]
This is an open question/discussion.

EOL of Python 2 is 2020.
Should we support Python 2 till then?

**Comment by sergiomb2** [comment]
For me the biggest problem when run with python3 is : 
WARNING: subdownloader.modules.metadata # No metadata module available.

If we could get one  metadata module on python3 , for me we can just support python3

**Comment by madebr** [comment]
A warning is just that, a warning. No error yet.
The warning is not printed anymore since d1daaf37e01ca7eeaff16050f494e633f25999ec.

**Comment by sergiomb2** [comment]
ok but pymediainfo replaces well kaa.metadata ?

**Comment by madebr** [comment]
When I compare the recent commit history of [kaa-metadata](https://github.com/freevo/kaa-metadata) and [libmediainfo](https://github.com/MediaArea/MediaInfoLib),
I have more confidence in libmediainfo.

(pymediainfo wraps libmediainfo)

**Comment by sergiomb2** [comment]
ok so lets use python3 , I will try add modules pymediainfo, Fedora already have libmediainfo ...

**Comment by madebr** [comment]
Python 2 support has been abandoned.

**Comment by sergiomb2** [comment]
> Python 2 support has been abandoned.

That is a good new :smiley:
