### ISSUE TITLE
No UI (or error) if PyQt4 is missing

### ISSUE THREAD

**Issue by whizabz** [subdownloader/subdownloader#35]
### Description of problem
If PyQt4 is not available on the system, the UI doesn't open at all and doesn't throw an error either.

### How reproducible
Can be easily reproduced by removing PyQt4 from the system.

### Steps to Reproduce
  1. Remove PyQT4 from the system using `apt remove python-qt4`
  2. Run the application from the Menu item. (UI won't open)
  3. Run the application from the command line. (Will show an error)

### Actual Behavior
```
$ subdownloader
Traceback (most recent call last):
  File "/usr/bin/subdownloader", line 42, in <module>
    import gui.main
  File "/usr/share/pyshared/subdownloader/gui/main.py", line 9, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
```

### Expected Behavior
Should open the subdownloader GUI

### Version Info
  - SubDownloader Version: 2.0.18
  - Python Version: 2.7.15rc1
  - Operating System: Linux Mint 19.1 (Based on Ubunut 18.04)

### Additional info
- End users can install PyQt4 to get the application to run using `apt install python-qt4`, but there's no way for them to know why the UI isn't showing up unless they use the terminal.

(First time submitting an issue on GitHub. Please let me know if there's something I can correct)

**Comment by madebr** [comment]
Hello @whizabz 

Thanks for your patience!

The version of SubDownloader you're using (2.7.15rc1) is not a version we are supporting.
The upstream repo of your version is https://launchpad.net/subdownloader.

This repo is a fork that adds python3 and pyqt5 support.

**Comment by madebr** [comment]
I'm closing this issue.

If you installed pyqt4 and subdownloader using apt,
then running `apt remove pyqt4` should also remove subdownloader.

**Comment by mapreri** [comment]
It won't, because subbdownloader only *recommends* pyqt, doesn't depend on
it.  And it doesn't make sense to depend on it imho: subbdownloader can be
used without GUI just fine, and so the definition of recommends (something
that all but most unusual installation should install, as it requires a
manual intervention to not install recommends, to provide non-critical
functionality) fits perfectly here.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=639003

**Comment by mapreri** [comment]
That said, I'm fine with closing this issue: I don't think there is
anything that you can do to sanely message a graphical user when you miss
the graphic library you use...

**Comment by madebr** [comment]
Ok, I see the problem.
Let's introduce graceful failure.
I'll print something to stderr and add a call to `notify-send` somewhere.
```
notify-send -u critical -a SubDownloader -c ERROR "SubDownloader needs PyQt5" -t 2
```
Can you confirm that this would solve your problem?

**Comment by mapreri** [comment]
Well, indeed catching the Importer for exception and print a sane message
to stderr would already be something to do (currently if you try to
`subdownloader -g` without pyqt it crashes and throws a traceback at you).
That sounds something that you ought to do regardless.

Maybe you could notify-send something only when you detect stderr is not
attached to anything (i.e. it's running out of a terminal, perhaps launched
from a menu).  Thinking about it, another (perhaps uglier?) thing instead
of notify-send is to open a terminal showing the error message (For example
`$TERM bash -c "read -p 'you need to install pytqt5 to run subbdownloader
in graphic mode'"`).  Not sure, just thinking aloud, and as I said, I'm
perfectly fine with the current behaviour as well myself; maybe you can
wait for the reporter.

**Comment by madebr** [comment]
I've pushed something in 55ea5480bef36a4e1d97a1b00554f4a3a039f23b
If the solution is not adequate, please reopen.

**Comment by mapreri** [comment]
I think that's great, thank you!

Only one thing I realize now: you used `-t 2`, but that will make the message stay for *2 millisecond*!  I suggest you just drop the -t, so the user has to ack the message for it to go away.

**Comment by madebr** [comment]
Thanks for the feedback!
I removed the timeout as you suggested.
