### ISSUE TITLE
.desktop file mismatches

### ISSUE THREAD

**Issue by mapreri** [subdownloader/subdownloader#37]
This is a very old problem, an example of which is reported at [https://bugs.launchpad.net/ubuntu/+source/subdownloader/+bug/1001689](https://bugs.launchpad.net/ubuntu/+source/subdownloader/+bug/1001689) - however it is still true (even if it has long since been workarounded in Debian…)

The .desktop file contains:
```
Exec=subdownloader -g
MimeType=video/avi;
```

That makes it so that file managers associate the program with avi files, and allows to "open them" with subdownlaoder.  However, the Exec line doesn't have the `-V %f` option to take in on the file as a parameter.

One way around, which has been employed in Debian, is to just drop the MimeType line, but I consider that a subpar solution.

We also can't just add `-V %f` to the Exec line, as it would result in subdownloader being launched with an empty -V flag, causing an error.

One solution would be to accept a non-option argument (I think currently subdownlaoder is not accepting any?) and treat it as a video if it's passed.  I quickly checked if [additional actions](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html#extra-actions-keys) could help here, but I don't seem to find a way for them to be useful.

**Comment by madebr** [comment]
I just checked and I can make the `-V` option accept zero or more arguments (as opposed to one or more currently).
Would the patches in this branch fix this problem? https://github.com/madebr/subdownloader/tree/desktop_fix
I suppose I don't need to surround the `%f` options with double quotes?

**Comment by mapreri** [comment]
> I just checked and I can make the `-V` option accept zero or more arguments (as opposed to one or more currently).
> Would the patches in this branch fix this problem? https://github.com/madebr/subdownloader/tree/desktop_fix

I think it would, yes.

> I suppose I don't need to surround the `%f` options with double quotes?

Looking around at the several .desktop on my computers, nobody seems to do it, so I suppose you do not.  The [specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html) says that "Field codes must not be used inside a quoted argument, the result of field code expansion inside a quoted argument is undefined." so it feels a bad idea to add the quotes :)

**Comment by madebr** [comment]
Fixed in 7c51909b9cc29f58fe08d9329dc83d2fc679aa56
