### ISSUE TITLE
Possible unwelcome exception in SDService.py

### ISSUE THREAD

**Issue by mapreri** [subdownloader/subdownloader#38]
Originally reported at [https://bugs.launchpad.net/ubuntu/+source/subdownloader/+bug/766536](https://bugs.launchpad.net/ubuntu/+source/subdownloader/+bug/766536)

In a very old installation with 2.0.14,

```pybt
Traceback (most recent call last):
  File "/usr/share/subdownloader/gui/main.py", line 904, in onButtonSearchSelectVideos
    self.SearchVideos(fileNames)
  File "/usr/share/subdownloader/gui/main.py", line 809, in SearchVideos
    videoSearchResults = self.OSDBServer.SearchSubtitles("",videos_piece)
  File "/usr/share/subdownloader/modules/SDService.py", line 423, in SearchSubtitles
    return SearchSubtitles (language, videos, imdb_ids)
  File "/usr/share/subdownloader/modules/SDService.py", line 70, in __call__
    raise e
error: [Errno 110] Connection timed out
```

Looking at the code now, I see that it changed a bit, but it still re-rises the exception.
I think a time out is a common enough occurrence that you should at least handle that one gracefully (even if it's my personal behaviour that applications should always do their outmost best to prevent crashes in all possible cases).

I'll be fine if you prefer to just close this bug as wontfix, I'll follow suit in the Ubuntu bug report.

**Comment by madebr** [comment]
`SDService.py` is retired in current master (2.2.0+) and we test for socket.error in there.
https://github.com/subdownloader/subdownloader/blob/df46a995d2c13db3f1f6bc2ee34bfad03f8bd04a/subdownloader/provider/opensubtitles.py#L487

For the 2.1, socket.error was missing and I have just added it in f4e4a5964497b5dc3cf5874fd7934e5374cbe989
https://github.com/subdownloader/subdownloader/blob/f4e4a5964497b5dc3cf5874fd7934e5374cbe989/subdownloader/provider/SDService.py#L355

I believe this should solve original bug.
