### ISSUE TITLE
Index out of range on client

### ISSUE THREAD

**Issue by TupaNegreiros** [subdownloader/subdownloader#40]
### Description of problem
When no subtitle is found, the client try to download first subtitle, number zero, and returns a error.

### How reproducible
Search for a subtitle for a file that you know there is no results.

### Steps to Reproduce
python3 /opt/subdownloader/subdownloader.py -c -V "/pathwithvideos" -l en

### Actual Behavior
Returns a error, if you search for folder, it will stop on first video.

### Expected Behavior
Returns "no subtitle found" and keep searching for another videos in the list.

### Version Info

  - SubDownloader Version: 2.1.0
  - Python Version: 3.7.3 (using python3 to call)
  - Operating System: Raspbian

### Additional info
None for now.

**Comment by TupaNegreiros** [comment]
Not sure how to reproduce. Now I've tried one file per call, I got results like:
`Video has no subtitles. Skipping.
Number of subs to download: 0`

But if I try the folder, I got the error:
`Search finished.
- Star.Wars.Rebels.S01E08.1080p.BluRay.x264-YELLOWBiRD.mkv
Video has no subtitles. Skipping.
- Star.Wars.Rebels.S01E06.1080p.BluRay.x264-YELLOWBiRD.mkv
Video has no subtitles. Skipping.
- Star.Wars.Rebels.S01E09.1080p.BluRay.x264-YELLOWBiRD.mkv
Video has no subtitles. Skipping.
- Star.Wars.Rebels.S01E01.1080p.BluRay.x264-YELLOWBiRDmkv.mkv
Auto-selecting first subtitle. (Use interactive mode to select another subtitle.)
Index out of range.`


I think is because I search for PB language, Star.Wars.Rebels.S01E01... has no PB subtitles, but has one EN subtitle.

**Comment by TupaNegreiros** [comment]
> I have just tested current master and it will search subtitles for each file.
> At the end, no subtitles were found and 0 subtitles are downloaded.
> 
> ```
> $ subdownloader -c -l en -V folder/
> Log in successful.
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
> 2/0 videos/subtitles have been found
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
> Search finished.
> - VIDEO 2.avi
> Video has no subtitles. Skipping.
> - VIDEO.avi
> Video has no subtitles. Skipping.
> Number of subs to download: 0
> ```
> 
> Isn't this the behavior you're looking for?

This is the expected. I think the problem occurs when no subtitles are found for the language you look for, but there are avaiable subtitles for any other languages.

**Comment by madebr** [comment]
I think I fixed your problem.
Indeed, when the filter did not match any subtitles the program would bail out and exit prematurely.

```
$ subdownloader -c -l fr -i -V dir1
Log in successful.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
1/2 videos/subtitles have been found
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
Search finished.
- VIDEO.mp4
Video has no subtitles that match your filter. Skipping.
Number of subs to download: 0
```

```
$ subdownloader -c -l fr -i -V dir2
Log in successful.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
1/0 videos/subtitles have been found
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100% Time: 0:00:00
Search finished.
- VIDEO2.avi
Video has no subtitles. Skipping.
Number of subs to download: 0
```

**Comment by TupaNegreiros** [comment]
Yes, solved. Thank you!
